### ISSUE TITLE
Adding CineCameraActor as a child of another actor

### ISSUE THREAD

**Issue by mrnelson6** [disguise-one/RenderStream-UE#16]
I am trying to create an experience where the camera will fly across the globe and give the physical camera controlling the disguiese/cine camera freedom to do small movements or rotations while the overall experience still is flying across the globe.

I thought this seemed easiest to put the CineCameraActor with the RenderStreamDefinition as a child to an Actor that will actually move across the globe. However, I seem to have a misunderstanding of how the CineCameraActor is inheriting rotation from the Parent Actor which is resulting the image being shown on the XR stage to not be in the direction/position I am expecting it to be.

I need to figure this out within the next couple of days so any information will be greatly appreciated.

Here is a gif of the CineCameraActor moving thru the Himalayas in editor mode. This is how I want it to appear on the XR stage but it is not.
![everestflyover](https://user-images.githubusercontent.com/26745036/124020772-95bab200-d99f-11eb-907d-3976f3eb3fbf.gif)

**Comment by makkbe** [comment]
@mrnelson6 the way we have solved this internally is through a slightly different parenting structure. The RenderStream CineCameraActor is parented to another CineCameraActor, which in turn is parented to an Empty Actor. We then have a LevelSequence with a CameraCuts track affecting the "middle" CineCameraActor. 
<img width="459" alt="Screen Shot 2021-06-30 at 20 22 26" src="https://user-images.githubusercontent.com/89238/124060037-fc13f480-d9e0-11eb-8acc-dc78ea38f2b9.png">

**Comment by mrnelson6** [comment]
Ok, so to make sure I understand this correctly, the top level Emtpy Actor is never moved and remains at 0,0,0 while I can apply translation/rotations to the middle Actor (NBA Camera) and the RenderStream will handle moving the final Camera (Disguise_BP_Camera)

**Comment by makkbe** [comment]
Yes, the top-level Empty Actor is positioned where you want your CineCameraActor to spawn. The second level CineCameraActor is at 0,0,0 relative to its parent, and RenderStream will affect only the CineCameraActor (also positioned at 0,0,0 relative to its parent) at the lowest level in the hierarchy.

**Comment by makkbe** [comment]
Question has been answered.
