### ISSUE TITLE
Merge r1.27_UE4.26 and r1.25_UE4.27 branches to create a r1.27_UE4.27 branch for testing

### ISSUE THREAD

**Issue by pkirkup-disguise** [disguise-one/RenderStream-UE#19]
As UE 4.27 will be released soon, we should ensure renderstream 1.27 is compatible with UE4.27.  Currently all 4.27 testing has occurred in renderstream 1.25.

**Comment by husberg-disguise** [comment]
r1.27_UE4.27 branch created and undergoing testing
