### ISSUE TITLE
Additional visibility support

### ISSUE THREAD

**Issue by MunWolf** [disguise-one/RenderStream-UE#2]
Currently there are 2 limitations with visibility
- Hard to modify multiple actors at once.
- Impossible to change visibility on actors that do not support adding components

**Comment by MunWolf** [comment]
![image](https://user-images.githubusercontent.com/3696546/118846290-7b7fb580-b8c4-11eb-98e4-4d051b4eb7f5.png)
![image (1)](https://user-images.githubusercontent.com/3696546/118846314-80446980-b8c4-11eb-9ea3-da81a6eab9e9.png)

Added this in, the workflow is as follows.
1. Lock the inspector window so it doesn't change with the selection.
2. Select the actors you want to add either in the viewport or through the outliner widget.
3. Right click the 'Force Visible' or 'Force Hidden' row.
4. Click 'Add from Selection'
Visibility components have been removed and all visibility logic/UI moved to the Definition component.

Note: This also means the blueprint methods that were previously used to change/query visibility are now moved to the Definition component and take the actor you want to query/change as a parameter.
![image](https://user-images.githubusercontent.com/3696546/118846248-70c52080-b8c4-11eb-9514-6191dc4b4951.png)

**Comment by husberg-disguise** [comment]
Will this break existing projects? Do we need an upgrade path?

**Comment by MunWolf** [comment]
It will break them in the sense the components will disappear and they have to add the actors they want to change the visibility of to the definition component.
That is the only thing that should break (at least that was my experience trying it)
