### ISSUE TITLE
UE4.27 plugin (probably) doesn't support DLSS

### ISSUE THREAD

**Issue by husberg-disguise** [disguise-one/RenderStream-UE#25]
The UE4.27 plugin's URenderStreamViewportClientwas recreated from nDisplay's UDisplayClusterViewportClient which leaves out the DLSS hook in UGameViewportClient. Add it back in and confirm DLSS works.

**Comment by MunWolf** [comment]
Fixed in https://github.com/disguise-one/RenderStream-UE/commit/64e4375b2f9203968250c967c4a8f47e7ea1b20e
