### ISSUE TITLE
vignetting on default cinecamera

### ISSUE THREAD

**Issue by noxy-k** [disguise-one/RenderStream-UE#46]
Hi,

While setting up any kind of project (r20) the default camera outputs with vignetting although none is set on it.
A workaround currently is to set vignetting size and strength to 0 on the camera on UE side, this seems to bypass whatever d3 is asking for. This works only with the rendering strategy set to fullscreen. Tiling/manual does not work and keeps the camera vignetting.

This probably happens when D3 copies the camera and passes its own arguments. There might be other similar arguments that I haven't identified yet that are being passed.
Is it possible to check/remove those defaults?

Thanks!

**Comment by chrisnashdisguise** [comment]
Hi, we haven't seen this before. We just copy the camera as it is set in UE, so if it has vignetting applied that will be retained, but if it doesn't then there shouldn't be any. We don't pass any arguments to do with vignetting specifically.

**Comment by noxy-k** [comment]
thanks for getting back to me so fast Chris.
Indeed tested on blank project and I don't get the issue - on both fullscreen and tiling. It's still somewhere on other projects so it's weird - might be a manipulation on UE side we've made.

**Comment by twhittock** [comment]
There are a few places it could be coming from - player controller or post processing volumes come to mind, but there are plenty of ways of adding post-processing to a camera view in UE. I hope that helps, I'll close the ticket now.
