### ISSUE TITLE
Maps workflow in 1.29_v1

### ISSUE THREAD

**Issue by noxy-k** [disguise-one/RenderStream-UE#47]
Hi,

Is the map selection workflow working properly in 1.29?
We had to update to 1.29 for r20.3 (preview) and it doesn't looks like the plugin generates the maps .json. I tried manually creating it and while it works for the default map, additional maps just dont work at all - returning an "INVALID" argument in d3.

**Comment by chrisnashdisguise** [comment]
Hi, there is very little difference between plugin versions 1.28 and 1.29 so I would be surprised if updating the plugin caused an issue, but it's possible there is a bug in the r20.3 prerelease. I'll investigate internally and let you know.

**Comment by chrisnashdisguise** [comment]
Are you making sure to load each map at least once and hitting 'Save Current' as you do so?
The channel/schema for the map will only be written to the JSON if you load and save it.

**Comment by noxy-k** [comment]
I've just tested again on a blank project, created two maps and some channel definitions on each. Load + save.
No .json file created by renderstream plugin.

**Comment by chrisnashdisguise** [comment]
Do you have a d3 license on the machine? After discussing this internally it seems it should still generate json files without a license, but if it's not then there could be a bug.

**Comment by twhittock** [comment]
I just tried a blank UE project without a d3 license. I hit 'save current' in UE, json was saved fine. Is there anything in the log files relating to renderstream?

**Comment by noxy-k** [comment]
I tested 2 different machines:
Machine A - regular computer, no d3 license - no json being generated and the following appears in log:
`LogRenderStreamEditor: Warning: RenderStreamLink unavailable, skipped GenerateAssetMetadata`

Machine B - RX render node with all licenses - json generated as expected after saving any map.

**Comment by twhittock** [comment]
That sounds like d3 isn't installed on Machine A. It's a requirement to have d3 installed - it doesn't have to be licenced, just available - all the json saving code is built into d3's install.

**Comment by noxy-k** [comment]
Yep confirmed it works fine after installing  d3 - is this mentioned anywhere or simply assumed?

**Comment by twhittock** [comment]
Hi. Yes, this is documented in the plugins section of the user guide - https://help.disguise.one/Content/Configuring/Render-engines/RenderStream-Unreal.htm but it could do with being clearer.

**Comment by noxy-k** [comment]
This is solved and can be closed :)
