### ISSUE TITLE
Actor BP Variable not visible in json

### ISSUE THREAD

**Issue by avanalle** [disguise-one/RenderStream-UE#57]
I am having an issue when referencing actor variables from the Level BP. In my case I am trying to expose "Solar Time" which is created by the SunSky Actor BP. I have tried direct reference and casting to the BP. Setting the default value of the variable using either method in the Level BP alters the world but the variable never appears in the .json file for control in d3. 

I am able to bypass SunSky Actor BP variables and expose parameters of its components as expected. E.g. can expose directional light component intensity as variable in Level BP.

**Comment by avanalle** [comment]
Issue persists with v5. Not certain if this is operator error.

**Comment by MunWolf** [comment]
With the current implementation of remote parameters we only support variables defined in Level BP.
