### ISSUE TITLE
Editor crash UE5.1.1 rs1.30 v6

### ISSUE THREAD

**Issue by Schurke** [disguise-one/RenderStream-UE#65]
Hi, RS team. We're experiencing an (unfortunately blocking) editor crash in our new Unreal 5.1.1 project connected to the rs1.30 v6 plugin. 

(Note that this is our first implementation of rs1.30 -- previous projects used rs1.29 so it's hard to speak to when this may have been introduced).
(Also note that our projects use RenderStream to bridge nDisplay content rather than single camera content).

![image (2)](https://user-images.githubusercontent.com/4356133/225162339-b1d95e92-5803-4ebb-953b-fff94df58fbb.png)

Seemingly the plugin is attempting to resize a vector but that vector's max_size() is -1 and it's choking on the operation.

Here's the most straightforward path to reproduction followed by a secondary path for comparison:

**Steps:**

1. Create a fresh ndisplay/workload/stream config from Disguise r23 (single node mapping on to a single display, retrieve the .ndisplay file from the renderstream_workloads folder)
2. UE5.1.1 project with rs1.30 latest enabled: Create a new nDisplay configuration asset.
3. Import .ndisplay file into asset.
4. Result: Editor crashes with the above exception (I did a bit of logging to console: it's trying to resize m_schemaMem which has a max_size() of -1 for some reason)
5. Observe: File contains a PostProcess json object with type: renderstream_capture defined

**Modified Steps for Confirmation:**

1. Create a fresh ndisplay config in Unreal 5.1.1 directly (rs1.30 latest enabled)
2. Setup a single node and mesh-based mapping using the editor
3. Observe: nDisplay preview working / reprojecting as expected in editor preview window
4. Add Custom Output Settings "rs" w/ type "renderstream_capture"
5. Result: Editor crashes with the above exception

![image (3)](https://user-images.githubusercontent.com/4356133/225163037-ff027848-fdbd-4610-bbcd-d1a75651822a.png)

So... it seems as though the codepath in the renderstream plugin doesn't execute until the "rs"/"renderstream_capture" key is present... as to why it's having trouble with the vector however...

**Comment by MunWolf** [comment]
This has now been fixed, and is included in the r1.30 UE5.1 v7 pre-release (which will be out soon)

**Comment by MunWolf** [comment]
https://github.com/disguise-one/RenderStream-UE/releases/tag/r1.30_UE5.1_v7
Pre-release out now
