### ISSUE TITLE
Unable to Run r24+

### ISSUE THREAD

**Issue by DNPTypho** [disguise-one/RenderStream-UE#66]
After updating to r24 I am unable to open any of my D3 projects, everything was working just fine in r23.4.2 but in r24, r24.0.1, and r24.0.2 my Disguise software freezes and crashes my PC while attempting to open.

This is a link to a Google Drive folder with my System and Project Diagnostic files: https://drive.google.com/drive/folders/1E5648SSdQLEFlszR0wEst7Pm_eXLrbW_?usp=sharing

The LED volume in our studio is running on r24.0.1 and my coworker on his own machine was able to run r24.0.1/2 without any issues so I am wondering if it's possibly a hardware issue on my system.

When opening a D3 project it would either freeze on the black loading screen or open the project for just a second before freezing and locking up my entire PC. If there's anything else I can provide to assist with this please let me know.

**Comment by chrisnashdisguise** [comment]
Hi, this seems like a core D3 issue rather than Renderstream plugins. I'd recommend you contact support@disguise.one and they should be able to help you out.
